### ISSUE TITLE
pretrained_models/resnet18.pth resnet34.pth not work 

### ISSUE THREAD

**Issue by alchowiw** [princetonvisualai/What-is-Dataset-Distillation-Learning#1]
Great work! Thanks for your contribution.
I encountered some problems during the operation. After I downloaded the pretrained_models in Google drive, I got an error when running experiment_code/replacement_analysis/pretrained_visuaztion.ipynb:
---------------------------------------------------------------------------
RuntimeError Traceback (most recent call last)
Cell In[5], line 16
14 train_model = Resnet18_Cifar10().to(device)
---> 15 train_model.load_state_dict(torch.load(f"../../pretrained_models/resnet18.pth"))
16 device = torch.device('cuda' if torch.cuda.is_available()else 'cpu')
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

 After I downloaded url="https://download.pytorch.org/models/resnet18-f37072fd.pth" and changed the path, an error was reported: 
 ---------------------------------------------------------------------------
 RuntimeError Traceback (most recent call last) 
 Cell In[7], line 15 12 return x 14 train_model = Resnet18_Cifar10().to(device)
 ---> 15 train_model.load_state_dict(torch.load (f"../../pretrained_models/resnet18-f37072fd.pth")) 
 16 device = torch.device('cuda' if torch.cuda.is_available()else 'cpu') 17 train_model.eval() 
 RuntimeError: Error(s) in loading state_dict for Resnet18_Cifar10: Missing key(s) in state_dict: "resnet.conv1.weight", "resnet.bn1.weight", "resnet.bn1.bias", "resnet.bn1.running_mean", "resnet.bn1.running_var", "resnet.layer1.0.conv1.weight", "resnet.layer1.0.bn1.weight", "resnet.layer1.0.bn1.bias", "resnet.layer1.0.bn1.running_mean", "resnet.layer1.0.bn1.running_var", "resnet.layer1.0.conv2.weight", "resnet.layer1.0.bn2.weight", "resnet.layer1.0.bn2.bias", "resnet.layer1.0.bn2.running_mean", ...
 
What should I do to solve this problem? Looking forward to your reply

**Comment by yang-william** [comment]
Hi, thank you for pointing out the issue. I think there was an issue while uploading that corrupted the models. I reuploaded the models to the google drive and it should work after downloading now. 

Here are also the md5 checksum for the model pth files to ensure it is properly downloaded:
resnet18: e14479e59c21d79a1cea1711fc02b38a
resnet34: 43886ad117cc3dc2bf152600044ced42

**Comment by alchowiw** [comment]
Thank you for your response!
I have changed the code to the following and it worked successfully:
```
train_model = Resnet18_Cifar10().to(device)
pretrained_dict = torch.load(f"../../pretrained_models/resnet18-f37072fd.pth")
model_dict = train_model.state_dict()
pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
model_dict.update(pretrained_dict)
train_model.load_state_dict(model_dict, strict=False)
```
Anyway, very grateful for your reply and answers!
